import '@/app/globals.css';

import { Inter } from 'next/font/google';
import { SideNav } from '@/app/components/parts/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-center mx-auto min-h-screen sm:gap-5 sm:max-w-[772px] sm:px-4'>
          <nav className='w-60 shrink-0 hidden sm:block'>
            <SideNav />  
          </nav>
          <main className="mx-auto flex-1 sm:border-x sm:border-mauve-6 relative pb-footer sm:max-w-[30rem]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};